import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { MainContainer } from '@/components/shared/MainContainer/MainContainer'
import { Hero } from '@/components/shared/Hero/Hero'
import { GetStaticProps } from 'next'
import { nextClient } from '../../lib/client'
import {
	GetLayoutQuery,
	GetProductTagsQuery,
	GetProductsQuery,
	ProductFragment,
	ProductTagsFragment,
} from '../../lib/generated/sdk'

interface PageProps {
	products: ProductFragment[]
	tags: ProductTagsFragment['edges']
}

export default function Page(props: PageProps) {
	const { products, tags } = props

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Hero />
			<MainContainer tags={tags} products={products} />
		</>
	)
}

export const getStaticProps: GetStaticProps = async () => {
	try {
		const layoutQuery = nextClient.getLayout()
		const productsQuery = nextClient.getProducts()
		const tagQuery = nextClient.getProductTags()

		const [layout, products, tags] = await Promise.allSettled([
			layoutQuery,
			productsQuery,
			tagQuery,
		])

		return {
			props: {
				layout: (layout as PromiseFulfilledResult<GetLayoutQuery>).value,
				products: (products as PromiseFulfilledResult<GetProductsQuery>).value
					.products.nodes,
				tags: (tags as PromiseFulfilledResult<GetProductTagsQuery>).value
					.productTags.edges,
			},
		}
	} catch (error) {
		return {
			notFound: true,
		}
	}
}
